name: Node & Docker CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # ─── API deps ───────────────────────────────────────────
      - name: npm ci (root)
        run: npm ci --ignore-scripts

      # ─── Client deps & build ───────────────────────────────
      - name: npm ci (client)
        run: npm ci --prefix client --ignore-scripts

      - name: Build React
        run: npm run build --prefix client
        env:
          CI: ""          # override GitHub’s CI=true

      # ─── API tests (optional) ──────────────────────────────
      - name: Run API tests
        run: npm test --if-present

  
