name: Node & Docker CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]        # keep in sync with Dockerfile

    steps:
      # 1️⃣  Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣  Install Node + use npm cache
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3️⃣  Install API deps (root)
      - name: npm ci (root)
        run: npm ci --ignore-scripts

      # 4️⃣  Install client deps
      - name: npm ci (client)
        run: npm ci --prefix client --ignore-scripts

      # 5️⃣  Build React **without failing on warnings**
      - name: Build React
        run: npm run build --prefix client
        env:
          CI: ""                        # <- overrides GitHub’s CI=true

      # 6️⃣  Run tests (skips if none)
      - name: Run API tests
        run: npm test --if-present
      - name: Run client tests
        run: npm test --prefix client --if-present

  # ---------- OPTIONAL: build Docker images ----------
  docker-build:
    if: github.event_name == 'push'     # run only on main pushes
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: docker compose build (prod profile)
        run: docker compose --profile prod build
